# Generated by Django 3.2.16 on 2022-10-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=100)),
                ('certificate_link', models.CharField(max_length=100)),
                ('certificate_issuer', models.CharField(max_length=100)),
                ('certificate_issue_year', models.IntegerField(max_length=4)),
                ('certificate_issue_month', models.IntegerField(max_length=2)),
                ('certificate_issue_date', models.IntegerField(max_length=2)),
            ],
        ),
    ]
